### ISSUE TITLE
create a static mapping function

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/obisindicators#12]
* create a mapping function
    * different projections
    * create leaflet interactive map

**Comment by bbest** [comment]
`ggmap_metric(sf, column, …)`
Statically map a metric in a set of spatial features using ggplot

**Comment by bbest** [comment]
Now vignettes end with...

### Plot maps

Let's look at the resulting metrics in map form.

```r
gmap_metric(grid, "es", label = "ES(50)")
gmap_metric(grid, "shannon", label = "Shannon index")
gmap_metric(grid, "n", label = "# of records", trans = "log10")
```

![a](https://user-images.githubusercontent.com/2837257/165564166-ebfa6107-3a3b-4515-ab5f-527798f95c40.png)

![b](https://user-images.githubusercontent.com/2837257/165564196-142c80ca-bd0e-432a-94fd-bfad3eb5ad2d.png)

![c](https://user-images.githubusercontent.com/2837257/165564222-1b37ae2b-3822-41ab-bd11-854ecf80dcaf.png)
