### ISSUE TITLE
Create ES50 heatmap on globe website

### ISSUE THREAD

**Issue by MathewBiddle** [marinebon/obisindicators#39]
There is a really nice visualization tool at https://glaroc.github.io/gbif_globe/ and the source code is available at https://github.com/glaroc/gbif_globe.

It looks like you could replace the following two lines with references to your own jpg images.
https://github.com/glaroc/gbif_globe/blob/09e7ef973239e94db28838b87721058e0019fa83/src/App.js#L43-L44

If obisindicators could create the ES50 indicator for the globe and save the maps as jpg images, we might be able to use this visualization tool.

**Comment by MathewBiddle** [comment]
Pitched for OHW22

* https://github.com/orgs/oceanhackweek/discussions/4#discussioncomment-3374601

**Comment by MathewBiddle** [comment]
images need to be 16k by 8k px.

**Comment by MathewBiddle** [comment]
@albenson-usgs has the code https://github.com/USF-IMARS/global-obis-es50/blob/main/use_gbif_parquet_file.Rmd. Just need to update how the images are written (I think).

https://github.com/USF-IMARS/global-obis-es50/blob/9ad98caa7e2f6aef559985f5d24391bf8cc19d1f/use_gbif_parquet_file.Rmd#L115-L141

**Comment by MathewBiddle** [comment]
Okay, here's what I've learned:
* I've been able to project [this image](https://raw.githubusercontent.com/MathewBiddle/bio_ice/main/map_obis_2020.jpg)  of species density (as calculated and generated [here](https://github.com/MathewBiddle/bio_ice/blob/main/Create_species_map_from_OBIS_API.ipynb) - See cell 23) onto the globe.
* The projection that seems to fit is `PlateCarree()`. But, we might want to test with [other available projections](https://scitools.org.uk/cartopy/docs/latest/reference/projections.html).
* I had to make the background of the image transparent so the earth topology comes through. Otherwise it's just your map wrapped around a ball (in hindsight that might make this easier if we disregard the topology layer - wont need to match up projections and centers).

Below are some tinkerings with a small image:

![image](https://user-images.githubusercontent.com/8480023/186712153-c4e654ef-6e3d-428a-ad1f-8a168170153b.png)
![image](https://user-images.githubusercontent.com/8480023/186717995-6a7ddb7f-d3ee-4041-9194-792ec9cac53c.png)

**Comment by MathewBiddle** [comment]
you can see my progress at https://github.com/MathewBiddle/gbif_globe
- can't figure out how to build to gh-pages branch and publish to [mathewbiddle.github.io/gbif_globe](https://mathewbiddle.github.io/gbif_globe/)

**Comment by MathewBiddle** [comment]
Published! https://mathewbiddle.github.io/gbif_globe/

Note:
* only the first 2020 
![image](https://user-images.githubusercontent.com/8480023/186768724-1fc28fa3-2a94-46b0-80ca-a43d723ef5a1.png)
and 2010 ![image](https://user-images.githubusercontent.com/8480023/186768763-f9c1650b-f598-4b6c-9873-96bb3139dcbb.png)
 toggles have images.
* The projections are wrong for this display
* I removed the topography layer - too difficult to match up topography projection to data projection without knowing what it was originally.

**Comment by MathewBiddle** [comment]
Projection is [`PlateCarree`](https://scitools.org.uk/cartopy/docs/latest/reference/projections.html#platecarree)

![image](https://user-images.githubusercontent.com/8480023/186912292-56035244-88e5-4283-8975-8d41c237141a.png)

**Comment by MathewBiddle** [comment]
Checkout the [README](https://github.com/MathewBiddle/gbif_globe/blob/master/README.md) for details on how to create the images for projecting onto sphere.

**Comment by 7yl4r** [comment]
🔥 I am excited to see progress on this.

**Comment by 7yl4r** [comment]
ongoing development now over here: https://github.com/MathewBiddle/globe

Last piece before closing this is to add a link to it.

**Comment by MathewBiddle** [comment]
ANNNDD Here is the link to it: https://mathewbiddle.github.io/globe/
