### ISSUE TITLE
do more data subsets & make vignettes for them

### ISSUE THREAD

**Issue by bbest** [marinebon/obisindicators#8]

**Comment by 7yl4r** [comment]
* make some maps of ES50 (called `es` in output df) 
    * using global subset
    * using other spatial subsets
    * using full global data
    * using annual (or other datetime) subsets?
    * with different hex sizes
    * using taxa subsets

**Comment by 7yl4r** [comment]
We want to include interesting (and small) subsets in `/data/` and we want to create vignettes showing them off. My notes on creating vignettes

* create new vignettes via `usethis::use_vignette("new_vignette_name")`
* to pre-build a vignette
    * set chunk's `eval` is false
    * then put markdown into the vignette to display the output image (or other html)
    * assets go in `vignettes` or in `man/figures` [[ref](https://github.com/r-lib/pkgdown/issues/280#issuecomment-287645977))

we may want to divide this issue out into subissues focusing on some of the subset items above.

**Comment by 7yl4r** [comment]
@sonjagiardina made a really nice vignette on hex resolutions and I am working on one for temporal subsets.
